### ISSUE TITLE
`serve_static_files` allows any file to be inputed

### ISSUE THREAD

**Issue by Tobias-Opsahl** [NorthernTechHQ/student2023#16]
Team: livhilde & tobias-opsahl
The function `serve_static_files` in `server.py` can input any file, meaning that hackers can read any content.

**Comment by olehermanse** [comment]
What files can be exposed using this? Can you show an example?

**Comment by olehermanse** [comment]
Duplicate:

https://github.com/NorthernTechHQ/student2023/issues/19
