### ISSUE TITLE
Passwords are hardcoded in python

### ISSUE THREAD

**Issue by Tobias-Opsahl** [NorthernTechHQ/student2023#18]
Team: livhilde & tobias-opsahl

In `server.py`, passwords are hardcoded instead of being environment variables, making it easy to output with print statements. For example, the code uses `PG_PASSWORD = os.getenv("PGPASSWORD")`, making it possible to get the password simply with `print(PG_PASSWORD)`.

**Comment by olehermanse** [comment]
Duplicate: https://github.com/NorthernTechHQ/student2023/issues/8
