### ISSUE TITLE
list files in current directory

### ISSUE THREAD

**Issue by mineralsfree** [NorthernTechHQ/student2023#30]
team: whatever (sabeichm, lullu57, mineralsfree)
When we query `localhost:5000/static`, we for no good reason get the `ls` of current directory exposing filenames
![image](https://github.com/NorthernTechHQ/student2023/assets/23060634/b86246cd-7bb7-4361-8902-e222b842be14)

**Comment by sabeichm** [comment]
<img width="340" alt="Skjermbilde 2023-10-24 kl  19 02 16" src="https://github.com/NorthernTechHQ/student2023/assets/122891310/76b0bc78-7cd7-4941-8a8b-a5a81064177f">

<img width="272" alt="Skjermbilde 2023-10-24 kl  19 02 05" src="https://github.com/NorthernTechHQ/student2023/assets/122891310/0e2f9268-49d7-4f16-8205-2d7515378d57">
