### ISSUE TITLE
Integrity : Cookie change 

### ISSUE THREAD

**Issue by mineralsfree** [NorthernTechHQ/student2023#6]
Team: whatever (sabeichm, lullu57, mineralsfree)

If we change cookie in the "Application" tab of Dev tools  we can pretend that we are admins, there is no check for that!

**Comment by sabeichm** [comment]
<img width="1496" alt="Skjermbilde 2023-10-24 kl  18 18 08" src="https://github.com/NorthernTechHQ/student2023/assets/122891310/3d95b38a-7f29-450a-b039-3d7d662eb231">
